### ISSUE TITLE
Vault Consul Prod Rollout

### ISSUE THREAD

**Issue by jeffbyrnes** [evertrue/et_secrets-cookbook#2]
@andrhamm @maxkohl88 here’s my playbook on this rollout, which I’d love to tackle tomorrow if possible.

1. Spin up Consul & Vault cluster (`et_consul::server` & `et_secrets`)
2. Init the Vault
3. Pass out unseal keys to operators, save the root token to 1Pass Ops vault
4. Unseal the Vault instances
5. Create access policies:
    - [ ] apps
    - [ ] developers
    - [ ] devops
6. Enable & set up GitHub Auth & map teams:
    - [ ] developers
    - [ ] devops
7. Populate the Vault w/ the contents of old ZK-backed Vault:
    - [ ] dna
    - [ ] harbormaster
    - [ ] loading_dock
    - [ ] payments
    - [ ] payments-exporter?
    - [ ] salesforce-syncer
    - [ ] windlass
8. Generate & update `VAULT_TOKEN` for apps (i.e., with `{"policies":["apps"]})`)
9. Set `VAULT_TOKEN` and `VAULT_ADDR` to point to new Vault
10. Test out by re-deploying a non-critical, Vault-backed service:
    - [ ] loading-dock
11. Restart all other Vault-backed services to validate they will continue working well:
    - [ ] dna
    - [ ] harbormaster
    - [ ] loading-dock
    - [ ] payments
    - [ ] payments-exporter
    - [ ] salesforce-syncer
    - [ ] windlass

**Comment by andrhamm** [comment]
`payments` and `payments-exporter` both use the same key in vault

**Comment by jeffbyrnes** [comment]
Forgot this is a public cookbook, migrating this to `server-chef` just in case.
